### ISSUE TITLE
Wallet address Auto changes, the old address could not be found

### ISSUE THREAD

**Issue by hxl9654** [memorycoin/memorycoin#23]
There are some MMC in the wallet address of mine, but I don't know what happened, these MMC suddenly disappeared, and my wallet address changes. In the purse, left previous record of the transaction, and the amount to 0, other information is not visible. there were two computers running the MMC program, and the emergence of this issue. My old address is
MKvTSGrRqSQ5vrBfAqbTEz1kitXiG1miVM, which became MJrQaX9LkTaDTDrHoY5o4pwuGN73cPGYvr. I tried to restore the backup files, but does not solve the problem. I tried a the old and new version of the wallet, the problem still.

**Comment by hxl9654** [comment]
Do not know why, I can't upload picture here

**Comment by hxl9654** [comment]
http://qwgg9654.free3v.com/pic.html
I put Screenshot here
I tried to re download the block
Looking forward to your reply
My email address 568629794@qq.com

**Comment by FreeTrade** [comment]
Cannot reproduce.
